name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - master
    - develop
  tags:
    include:
      - v*
  paths:
    exclude:
    - '*.md'

pr:
  branches:
    include:
    - develop
    - master
    - release/*
  paths:
    exclude:
    - '*.md'

resources:
  repositories:
    - repository: templates
      type: github
      name: CluedIn-io/AzurePipelines.Templates
      endpoint: 'CluedIn-io'

pool:
  vmImage: 'VS2017-Win2016'
  
variables:
  Dotnet.Skip.First.Time.Experience: 'True'
  testFolderPath: '$(Build.SourcesDirectory)/test'

steps:
- template: crawler.default.build.yml@templates

- task: ArchiveFiles@2
  inputs:               # TODO Add condition to check /Documentation folder exists AND whether we have and changes
    rootFolderOrFile: '$(Build.SourcesDirectory)/Documentation'
    archiveType: 'zip' # Options: zip, 7z, tar, wim
    archiveFile: '$(Build.ArtifactStagingDirectory)/Documentation.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:             # TODO Same condition as above?
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: Documentation
